const guessedLetters = document.querySelector(".guessed-letters");
const guessButton = document.querySelector(".guess");
const textInput = document.querySelector("#letter");
const wordMaking = document.querySelector(".word-in-progress");
const remainingGuesses = document.querySelector(".remaining");
const remainingSpan = document.querySelector(".remaining span");
const messageParagraph = document.querySelector(".message");
const playButton = document.querySelector(".play-again");
const word = "magnolia";